### PR TITLE
Alexey Сhalapan hw1 task1

### PR DESCRIPTION
**Pull request by AlexeyChalapan**

### CODE REVIEW

**Review by SerGamEsNIUS — DISMISSED** [review]
Lgfm

**Review by Alexhorosko — APPROVED** [review]

**Review by NikolayLukashevich — DISMISSED** [review]
Good work!

**Review by Alexhorosko — DISMISSED** [review]

**Review by NikolayLukashevich — DISMISSED** [review]
Approve from me

**Review by NikolayLukashevich — APPROVED** [review]
Ok now

**Review by wnb911 — APPROVED** [review]

**Review by semantics96 — APPROVED** [review]

**Review by Alexhorosko — APPROVED** [review]

**Review by javaGuruBY — APPROVED** [review]
lgfm

**Pull request merged**
