### PR TITLE
Added Hw1Task1

### PR DESCRIPTION
**Pull request by SerGamEsNIUS**

### CODE REVIEW

**Review by maximzmei — APPROVED** [review]

**Comment by maximzmei** [comment]
lgfm

**Review by NikolayLukashevich — APPROVED** [review]
good, but you can make it better

**Comment by AlexanderSmirnov92** [comment]
Not bad, very nice)

**Comment by SerGamEsNIUS** [comment]
> good, but you can make it better

With pleasure will accept all adequate critics

**Review by a-vov4eg — APPROVED** [review]
Lgfm

**Review by AlexeyChalapan — APPROVED** [review]
good job

**Review by Alexhorosko — COMMENTED** [review]
Хорошая работа

**Pull request merged**
