### PR TITLE
Adding Hw1_Task2

### PR DESCRIPTION
**Pull request by Maria150**

### CODE REVIEW

**Review by NikolayLukashevich — DISMISSED** [review]
Good job. Approve from me.

**Review by wnb911 — APPROVED** [review]

**Review by AnastasiaKichaeva — DISMISSED** [review]

**Review by Alexhorosko — DISMISSED** [review]

**Review by wnb911 — DISMISSED** [review]

**Review by NikolayLukashevich — DISMISSED** [review]
Approve from me

**Review by NikolayLukashevich — DISMISSED** [review]
Ok now

**Review by NikolayLukashevich — APPROVED** [review]
Approve

**Review by wnb911 — APPROVED** [review]

**Review by AnastasiaKichaeva — APPROVED** [review]

**Review by javaGuruBY — APPROVED** [review]
lgfm

**Pull request merged**
