### PR TITLE
adding my first homework

### PR DESCRIPTION
**Pull request by sashalemeshonok**

### CODE REVIEW

**Review by Alexhorosko — APPROVED** [review]

**Comment by Marina2404** [comment]
Lgfm

**Review by AnastasiaKichaeva — APPROVED** [review]
LGFM

**Review by Maria150 — APPROVED** [review]

**Review by NikolayLukashevich — APPROVED** [review]
Approve from me

**Review by wnb911 — APPROVED** [review]

**Review by javaGuruBY — APPROVED** [review]
lgfm

**Pull request merged**
