### PR TITLE
Julia_Kozlowska_Hw1_Task2

### PR DESCRIPTION
**Pull request by yk72797**
Could you check my homework, please?

### CODE REVIEW

**Comment by yk72797** [comment]
Could you check my homework, please?

**Review by SerGamEsNIUS — APPROVED** [review]
Lgfm

**Review by NikolayLukashevich — APPROVED** [review]
All good. Nice job

**Review by DimaKachenya — APPROVED** [review]
lgfm

**Review by Maria150 — APPROVED** [review]

**Review by Alexhorosko — APPROVED** [review]

**Review by javaGuruBY — APPROVED** [review]
LGFM

**Pull request merged**
