### PR TITLE
Anastasia Kichaeva Hw1 Task1

### PR DESCRIPTION
**Pull request by AnastasiaKichaeva**

### CODE REVIEW

**Review by Maria150 — APPROVED** [review]

**Review by Marina2404 — APPROVED** [review]
Lgfm

**Review by AlexanderSmirnov92 — APPROVED** [review]
Not bad

**Review by NikolayLukashevich — APPROVED** [review]
lgfm

**Review by SergeyK92 — APPROVED** [review]
Look good for me

**Review by wnb911 — APPROVED** [review]

**Review by javaGuruBY — APPROVED** [review]
lgfm

**Pull request merged**
